package eDentify;

/* @author: 	Priscilla Nagashima Boyd (SRN 101007089)
 * 				Course: BSc Computing and Information Systems
 * 				Module: CIS 3320 (Project)
 * 				Title:  Managing an online identity: a privacy study of information
 * 				generated by publicly available data
 * 
 * @file:       Main.java
 * 
 * @desc:		This class provides the main function
 * 				to run the eDentify program.
 */

public class Main {
	
	static String name;
	static String county;
	static String country;
	
	public static void main(String[] args){
		CommandLineProcessing obj = new CommandLineProcessing();
		obj.showOptions();

		GoogleSearchRetrieval search = new GoogleSearchRetrieval();
		search.setQuery(name, county, country);
		
		System.out.println(name);
		search.getResults(); //Run search engine and get results
		
	}
}
